FROM ubuntu:22.04
RUN apt-get update && apt-get install -y git python3 python3-pip python-is-python3 && apt-get clean all

ARG APP_VERSION=v0.2.2
WORKDIR /apps/comfyui
RUN git clone https://github.com/comfyanonymous/ComfyUI.git -b ${APP_VERSION} /apps/comfyui
RUN pip install -r requirements.txt --no-cache-dir
CMD python main.py --listen --multi-user
