FROM ubuntu:22.04

RUN apt-get update && apt-get install -y wget git python3 python3-venv libgl1 libglib2.0-0 google-perftools bc && apt-get clean all
ARG APP_VERSION=v1.10.0
RUN wget -q https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/refs/tags/${APP_VERSION}/webui.sh -O webui.sh
